adafruit_requests.py

Adding `parse_headers` back from ESP32SPI_Requests.
Re, issue: https://github.com/adafruit/Adafruit_CircuitPython_ESP32SPI/issues/62
Code Output
```
code.py output:
ESP32 SPI simple web server test!
soft reboot
Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
ESP32 SPI simple web server test!
open this IP in your browser:  10.0.0.208
```

Add Parse_Headers Method Back

---

adafruit_requests.py

Addressing https://github.com/adafruit/Adafruit_CircuitPython_Requests/issues/6
Request now uses `parse_headers`. 
Tested with `WSGIServer.py` on Adafruit CircuitPython 4.0.0 on 2019-05-20; Adafruit PyPortal with samd51j20.
https://github.com/adafruit/Adafruit_CircuitPython_ESP32SPI/blob/master/examples/server/esp32spi_wsgiserver.py

Refactor request method to use parse_headers

---

adafruit_requests.py

Switching `socket.write` to `socket.send` to match the [CircuitPython Socket API](https://circuitpython.readthedocs.io/en/latest/shared-bindings/socket/__init__.html#socket.send) and the [CPython Socket API](https://docs.python.org/3/library/socket.html#socket.socket.send).
Related PR: https://github.com/adafruit/Adafruit_CircuitPython_ESP32SPI/pull/70

Switch to Socket.Send

---

adafruit_requests.py

Switching `socket.read` calls to `socket.recv`.
Related PR: https://github.com/adafruit/Adafruit_CircuitPython_ESP32SPI/pull/71

Use socket.recv

---

adafruit_requests.py

fixes #10 
tested on Raspberry Pi Zero (Buster) and on metro_m4_airlift_lite

 fix byte strings for Blinka compatibility

---

adafruit_requests.py

We now pre-fill the contents to an empty string

fix parsing error on lines like `b'X-Geo-Block-List:'` as received by github

---

adafruit_requests.py

In python3 with requests we can use code like this: 
```
import requests
URL = "https://docs.google.com/forms/u/0/d/e/1FAIpQLScoUhFA1BIJjXF2-QM_mxNMN62Y2BCJ--gwJIwWcwJPvWDlwQ/formResponse"
form_data = {
"entry.2004206042": "Hello",
"entry.487209416": "Binka"
}
r = requests.post(URL, data=form_data)
print(r.text)
```
And the data will get sent as form data. More specifically using the format:
`name=value&other_name=other_value`
and gets sent using `Content-Type: application/x-www-form-urlencoded`
This allows us to use a simple dictionary for our form data but submit it to web apps expecting data from an html `<form>` element. 
This change allows the circuitpython requests library to behave similarly. When `data` is a dictionary it will get formatted into the key/value string and sent with …

If data is dictionary send it as form data

---

adafruit_requests.py

As dicsussed in #20, the encoding parameter passed to the `byes` call gives a **TypeError: wrong number of arguments**

Removed encoding parameter from bytes call

---

examples/requests_advanced_ethernet.py
examples/requests_simpletest_ethernet.py

Adding a simpletest for the ethernet library. This will be used in a future Learning System Guide.
Requires: https://github.com/adafruit/Adafruit_CircuitPython_Wiznet5k/pull/7
Tested on:  `Adafruit CircuitPython 5.0.0 on 2020-03-02; Adafruit Metro M4 Express with samd51j19`
Test output:
```
code.py output:
Fetching text from http://wifitest.adafruit.com/testwifi/index.html
----------------------------------------
Text Response:  This is a test of Adafruit WiFi!
If you can read this, its working :)
----------------------------------------
Fetching JSON data from http://httpbin.org/get
----------------------------------------
JSON Response:  {'url': 'http://httpbin.org/get', 'headers': {'User-Agent': 'Adafruit CircuitPython', 'Host': 'httpbin.org', 'X-Amzn-Trace-Id': …
```

Add Simpletest for Ethernet Library

---

examples/requests_advanced_cellular.py
examples/requests_simpletest_cellular.py

Adding examples for using this library with a cellular (adafruit/Adafruit_CircuitPython_FONA#3) interface.
Tested with `Adafruit CircuitPython 5.0.0 on 2020-03-02; Adafruit Metro M4 Express with samd51j19`
```
code.py output:
Attaching to network...
Attaching to network...
..
Connecting to network...
Connecting to network...
Fetching text from http://wifitest.adafruit.com/testwifi/index.html
b'HTTP/1.1 200 OK'
----------------------------------------
Text Response:  This is a test of Adafruit WiFi!
If you can read this, its working :)
----------------------------------------
Fetching JSON data from http://httpbin.org/get
b'HTTP/1.1 200 OK'
----------------------------------------
JSON Response:  {'url': 'http://httpbin.org/get', 'headers': {'User-Agent': 'Adafruit CircuitPython', 'Host': …
```

Add Cellular Examples

---

examples/requests_advanced.py
examples/requests_advanced_cellular.py
examples/requests_simpletest_cellular.py

Updating Cellular examples for Adafruit Fona v2.0.0
https://github.com/adafruit/Adafruit_CircuitPython_FONA
--- 
`examples/requests_advanced_cellular.py`
```
code.py output:
Attaching to network...
Attaching to network...
Attaching to network...
Attached!
Connecting to network...
Network Connected!
Fetching JSON data from http://httpbin.org/get...
------------------------------------------------------------
Response's Custom User-Agent Header: Adafruit CircuitPython,blinka/1.0.0
------------------------------------------------------------
Response HTTP Status Code:  200
------------------------------------------------------------
Raw Response:  b'{\n  "args": {}, \n  "headers": {\n    "Host": "httpbin.org", \n    "User-Agent": "Adafruit CircuitPython,blinka/1.0.0", \n …
```

Update Cellular Examples for Adafruit FONA (3G/GSM)

---

.github/workflows/test.yml
adafruit_requests.py
examples/requests_advanced.py
examples/requests_advanced_cpython.py
examples/requests_github_cpython.py
examples/requests_https_cpython.py
examples/requests_simpletest.py
examples/requests_simpletest_cpython.py
tests/chunk_test.py
tests/header_test.py
tests/legacy_mocket.py
tests/legacy_test.py
tests/mocket.py
tests/parse_test.py
tests/post_test.py
tests/protocol_test.py
tests/reuse_test.py

Reusing sockets makes sharing memory easier and keeping the connection open will make them faster.
This PR also moves to a model of passing the socket and ssl implementation into `Session` instead of into the module with a function.
json parsing will now happen character-by-character on CircuitPython and lower the peak memory used and the largest allocation size.
It includes legacy compatibility so it *shouldn't* break anything. Corresponding libraries will benefit more from this when they implement `recv_into` so they don't allocate a new buffer every read.
This is draft because I need to:

Add HTTP1.1 support and socket reuse

---

adafruit_requests.py

Fixes #32 
@anecdata, mind reviewing this?

Fix 5.3.1 by providing find and json in one big chunk

---

adafruit_requests.py

we dont know how much is remaining if data is chunked, so avoid comparing `None` received

Toss out chunked data if we never read anything

---

examples/requests_https_cpython.py

https://wifitest.adafruit.com/testwifi/index.html doesn't work, only http:// does, so use https://httpbin.org/get fetched as text for now.
The actual fetch is currently commented out, but if uncommented, it would not work.

Don't use https://wifitest.adafruit.com/testwifi/index.html

---

adafruit_requests.py
tests/concurrent_test.py
tests/legacy_mocket.py
tests/legacy_test.py
tests/mocket.py
tests/reuse_test.py

* Handle send failures
* Handle send exception from ESP32SPI
* Handle failed response read
* Handle connect() failures
* Handle runtime error from ESP32SPI on connect

Better handle errors by retrying 

---

adafruit_requests.py
tests/chunk_test.py

The chunk line is read up to the terminating "\r\n", then any extensions are ignored by only using the string up to the first ";" (if any) when determining the length of the chunk.
Resources:
https://tools.ietf.org/html/rfc7230#section-4.1.1
https://www.boost.org/doc/libs/1_74_0/libs/beast/doc/html/beast/using_http/chunked_encoding.html
Thanks to @anecdata for asking on Discord why ";" was getting special treatment, leading to this investigation.  We don't know of a specific URL or service that is affected by this bug.

Add, test support for chunk extensions

---

adafruit_requests.py

Closes #52 
On CircuitPython, bytearray objects have no split method.  Emulate the specific form that we need.
Testing performed: tests still pass, _and_ it works on a device.

Fix CircuitPython compatibility

---

adafruit_requests.py
tests/legacy_test.py
tests/reuse_test.py

This allows us to retry with a new socket. This greatly reduces the likelihood of `Unable to read HTTP response.`

Don't trust send works. Do one recv before creating Response

---

adafruit_requests.py

There was a second case where a bytearray was being split. We need to use @jepler's fix there as well. 
Without this fix, when you would reuse your requests object you'd get an error.
```python
response = requests.get("https://io.adafruit.com/api/v2/time/seconds")
response = requests.get("https://io.adafruit.com/api/v2/time/seconds")
_last_response: <Response object at 3f7b3b20>
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/lib/adafruit_requests.py", line 613, in get
File "/lib/adafruit_requests.py", line 569, in request
File "/lib/adafruit_requests.py", line 277, in close
AttributeError: 'bytearray' object has no attribute 'split'
```

One more case for _buffer_split0

---

examples/requests_advanced.py
examples/requests_simpletest.py

Addresses https://github.com/adafruit/Adafruit_CircuitPython_Requests/issues/57 and fixes `RuntimeError: Cannot access content after getting text or json` error in `examples/requests_advanced.py`

Fix examples for ESP32SPI + SSL socket

---

adafruit_requests.py

Catch `OSError` along with `_SendFailed` to avoid `RuntimeError: Out of sockets` caused by `OSError: Failed SSL handshake`
Background:
[https://github.com/adafruit/Adafruit_CircuitPython_Requests/issues/63#issuecomment-771650173](https://github.com/adafruit/Adafruit_CircuitPython_Requests/issues/63#issuecomment-771650173)
This should address #67

Catch OSError to avoid socket leak

---

adafruit_requests.py

An `ETIMEDOUT` exception occurring on a `socket.recv_into` call in a Session request would leave the socket open, and after two occurrences, would get `RuntimeError: Out of sockets` and require a microcontroller reset.
```
Traceback (most recent call last):
File "code.py", line 675, in http_get
File "/lib/adafruit_requests.py", line 595, in get
File "/lib/adafruit_requests.py", line 572, in request
OSError: [Errno 116] ETIMEDOUT
Traceback (most recent call last):
File "code.py", line 675, in http_get
File "/lib/adafruit_requests.py", line 595, in get
File "/lib/adafruit_requests.py", line 572, in request
OSError: [Errno 116] ETIMEDOUT
Traceback (most recent call last):  
File "code.py", line 675, in http_get
File "adafruit_requests.py", line 595, in get
File "adafruit_requests.py", line …
```

Catch recv-into exception to prevent Out of sockets

---

adafruit_requests.py

Fixes problem when there are free sockets but are not closed when needed. See #73

fix out of sockets issue

---

adafruit_requests.py
examples/requests_simpletest_cpython.py

Follow 3XX status redirects with a new request. Parse the `location`
header for an absolute url, absolute path, or relative path. Replace or
amend the url from the original request and place a new request.
Expand the `requests_simpletest_cpython.py` example with new requests
utilizing the three supported types of redirects.
Note: We're using the httpbingo.org domain for redirects until
the following issue on httpbin.org is resolved:
https://github.com/postmanlabs/httpbin/issues/617
This has been tested on CPython 3.8 and an ESP32-S2 based MagTag board
with CircuitPython 6.0.

Add simple support for redirects

---

adafruit_requests.py

Fixes:
```py
>>> import adafruit_requests
Traceback (most recent call last):
File "code.py", line 1, in <module>
File "adafruit_requests.py", line 40, in <module>
ImportError: no module named 'types'
```
(Issue reported on discord with 1.10.3)

From types in the try/catch clause

---

.github/workflows/build.yml
.github/workflows/release.yml
.gitignore
.readthedocs.yaml
adafruit_requests.py
docs/conf.py
requirements.txt
setup.py
tox.ini

This PR fixes importing `adafruit_requests` in CPython by replacing the imports of various classes from `adafruit_esp32spi`, `adafruit_wiznet5k`, etc. (which weren't specified as requirements of `adafruit_requests` and thus caused importing `adafruit_requests` to fail due to not being available) with [protocols](https://mypy.readthedocs.io/en/stable/protocols.html) that describe the common structure of those types.
To help prevent the use of `adafruit_requests` in CPython from breaking in the future, this PR also adds a step to the Build CI job which uses tox to build the package and run its tests in a virtual environment.
I also tested the changes to `adafruit_requests.py` in CircuitPython by copying the file to the `lib/` folder of my MagTag device running the [COVID tracking …

Fix importing `adafruit_requests` in CPython

---

adafruit_requests.py

This change presents a short term improvement of the error messages that arise from fetching GZipped data from an API. The message has been changed to state the exact cause of the problem and let the user know the way to access the raw data.
Tested successfully on Feather TFT ESP32-S2 and CPython on Linux using this code (with slightly modified initialization on the Feather for the circuitpython way of setup):
```py
https = requests.Session(socket, ssl.create_default_context())
JSON_GET_URL = "https://analytics.usa.gov/data/live/realtime.json"
print("Fetching JSON data from %s" % JSON_GET_URL)
response = https.get(JSON_GET_URL)
print("-" * 40)
print("JSON Response: ", response.text)
print("-" * 40)
```
current version output (on CPython, it's very similar in CircuitPython but the error …

raise error indicating gzipped data

---

.pre-commit-config.yaml
adafruit_requests.py
tests/legacy_mocket.py
tests/mocket.py

Simplify and shorten the current code. I will have a further PR later that changes a bunch of thrown exceptions to allow for easier error handling.
- CircuitPython 7 supports `split()` on bytes and bytearrays. Remove hand-coded routines no longer needed.
- CircuitPython 6 supports streaming `json` decoding. Remove workaround for 5.x non-streaming decoding.
- Refactor the duplicated check for gzip content.
_Please_ test with your own wifi code - thanks. I tested this with the simple wifi testing code, and with the Google calendar example, but not with other examples.

Remove pre 7.0 compatibility; other cleanup

---

adafruit_requests.py

New black hated that space apparently 😖 
Also took the opportunity to resolve #107

Use typing_extensions.Protocol if needed

---

adafruit_requests.py
tests/chunked_redirect_test.py

I found that `Reponse._throw_away()` worked fine unless the bytes returned from `_recv_into()` wasn't the full size of the throw away buffer. Simple fix once I figured out what was happening. Also including a unit test the reproduces the problem.

Proposed fix for issue #103. Fixes an issue with _throw_away() and large chunked redirects.

---

adafruit_requests.py

Fixes the following `pylint` errors:
```
************* Module adafruit_requests
Error: adafruit_requests.py:67:12: W2301: Unnecessary ellipsis constant (unnecessary-ellipsis)
Error: adafruit_requests.py:71:12: W2301: Unnecessary ellipsis constant (unnecessary-ellipsis)
Error: adafruit_requests.py:75:12: W2301: Unnecessary ellipsis constant (unnecessary-ellipsis)
Error: adafruit_requests.py:87:12: W2301: Unnecessary ellipsis constant (unnecessary-ellipsis)
Error: adafruit_requests.py:96:12: W2301: Unnecessary ellipsis constant (unnecessary-ellipsis)
Error: adafruit_requests.py:105:12: W2301: Unnecessary ellipsis constant (unnecessary-ellipsis)
Error: adafruit_requests.py:117:12: W2301: Unnecessary ellipsis constant (unnecessary-ellipsis)
Error: adafruit_requests.py:127:8: W2301: …
```

Fix pylint errors

---

examples/requests_adafruit_discord_active_online.py
examples/requests_api_discord.py
examples/requests_api_github.py
examples/requests_api_twitter.py
examples/requests_api_youtube.py

Includes Youtube, Twitter, Github, and Discord examples.

Add API examples for various social media sites

---

adafruit_requests.py

CircuitPython 8 supports exception chaining, so that the original problem can be shown. Here's how it looks on desktop python3:
```
Traceback (most recent call last):
File "/home/jepler/src/bundle/libraries/helpers/requests/adafruit_requests.py", line 527, in _get_socket
sock.connect((connect_host, port))
ConnectionRefusedError: [Errno 111] Connection refused
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/jepler/src/bundle/libraries/helpers/requests/adafruit_requests.py", line 721, in get
return self.request("GET", url, **kw)
File "/home/jepler/src/bundle/libraries/helpers/requests/adafruit_requests.py", line 661, in request
socket = self._get_socket(host, port, proto, timeout=timeout) …
```

preserve last exception when things are going wrong

---

adafruit_requests.py

Here is a draft to read full responses that do not provide a Content-Length in the header and are not chunked. 
I was porting some working code from MicroPython which used [urequests](https://github.com/micropython/micropython-lib/blob/master/python-ecosys/urequests/urequests.py) to CircuitPython on a Pico W, and I was sad to see it break because of issue #38.
After some time sifting through the code of both libraries, it seems that the urequest library simply does a `usocket.socket().read()` [at line 20](https://github.com/micropython/micropython-lib/blob/master/python-ecosys/urequests/urequests.py#L20), whereas this library only reads a specific number of bytes from the response.
So here is my hack that fixes my specific use case while not breaking the unit tests.
If you think it is a …

Add support for response without Content-Length

---

examples/requests_api_discord.py
examples/requests_api_github.py
examples/requests_api_mastodon.py
examples/requests_api_steam.py
examples/requests_api_twitch.py
examples/requests_api_twitter.py

API example displays the sum total amount of time in hours and days playing video games on steam.

Steam API example

---

examples/requests_api_openskynetwork_private.py
examples/requests_api_openskynetwork_private_area.py
examples/requests_api_openskynetwork_public.py

Free public limit is 100 calls per day and maximum of 60 seconds each or you'll get temp banned. You get 4000 calls if you login but I haven't figured out how with a microcontroller yet. They have no token system and their API is primarily built for python & curl. It's a foot in the door for public access to flight data.

Add OpenSky-Network API example

---

examples/requests_api_discord.py

One API at a time. @kattni my contributions that have _API_ in the example file name are not included in any learn guides or documentation. This is a good way to take baby steps with the update to settings.toml by first changing all of my contributions over. 
Most likely @FoamyGuy will be reviewing this one again. This is the web scrape example that requires you to get the auth key from the request header with a browser developer tool. Still works fine.
Unsure if I should embed the Web Workflow credentials for getenv in the example or just wifi?

Update Requests Discord API example to use settings.toml

---

adafruit_requests.py
tests/chunk_test.py
tests/concurrent_test.py
tests/header_test.py
tests/post_test.py
tests/protocol_test.py
tests/reuse_test.py

When helping a member in the discord channel `#help-with-circuitpython`, I had made the mistake of thinking that this library didn't automatically deal with turning a `dict` into a `urlencoded` string. I had them convert it by hand and try and it worked.
As it turns out - it does, but also sends the header `Content-Type: application/x-www-form-urlencoded`, which some systems (`Spotify` as one) can't handle getting the header twice.
This would fix issue https://github.com/adafruit/Adafruit_CircuitPython_Requests/issues/148
Test:
```
from os import getenv
import adafruit_requests
import socketpool
import ssl
import wifi
wifi_ssid = getenv("CIRCUITPY_WIFI_SSID")
wifi_password = getenv("CIRCUITPY_WIFI_PASSWORD")
client_id = getenv("SPOTIFY_CLIENT_ID")
client_secret = …
```

Fix duplicate header issue

---

adafruit_requests.py

This stems from [this issue](https://github.com/adafruit/Adafruit_CircuitPython_AdafruitIO/issues/115) in `Adafruit_CircuitPython_AdafruitIO` that caused [this issue](https://github.com/adafruit/Adafruit_CircuitPython_Requests/issues/148) to be re-opened.
If this path looks good I will add tests for the changes.

Correctly handle headers of different types

---

adafruit_requests.py

The current code throws an exception during `close()` when it tries to convert an empty buffer (`chunk_header`).
This PR also adds an optional parameter `fast=False`. Passing `True` will skip reading.
This addresses #130 (also mentioned in #138)

close(): fix exception and enable fast-close

---

adafruit_requests.py
tests/method_test.py
tests/reuse_test.py

I tested on a `M4 Express + Airlift` and a `UM FeatherS3`. I tried every combination of switching hosts, partial reads, etc to see if I could get an error without reading the whole response and didn't get any errors

Don't read all on response.close()

---

examples/wifi/expanded/requests_wifi_api_discord.py

General code cleanup from last version including pretty serial hierarchy view. Added a few more endpoints. Updated with Connection Manager.
```
✅ Wifi!
| Attempting to GET Discord JSON!
| ✅ Discord JSON!
|  | Name: adafruit
|  | Description: Adafruit community
|  | Members: 38922
|  | Online: 4196
Finished!
Board Uptime: 129352.0
Next Update: 15 minutes
===============================
```

Update Discord Web Scrape Example with Connection Manager

---

examples/wifi/expanded/requests_wifi_api_fitbit.py

Added pretty serial hierarchy view, general code cleanup and improvements, more endpoints (added Watch Battery Percentage). Attempted to ensure it meets current syntax practices. Made some constants shouty to make Pylint happy. Added a way to reset NVM back to factory default and it turned into the easiest method for anyone adding new credentials for the very first use. NVM reset is a very nice and easy to use feature now.
```
📡 Connecting to WiFi...
✅ WiFi!
| MANUAL REBOOT TOKEN DIFFERENCE -------
| Requesting authorization for next token
| Next Token: b768b6a28dd890d123e83e86669f5b8913647946b1736f2b3577ee8baef420a6
| 🔑 Next token written to NVM Successfully!
| Attempting to GET Fitbit JSON!
| ✅ Fitbit Intraday JSON!
|  | Fitbit Date: 2024-03-17
|  | Fitbit Time: …
```

Update Fitbit API Example with Connection Manager

---

examples/wifi/expanded/requests_wifi_api_rocketlaunch_live.py

The free API returns data on the next 5 scheduled rocket launches. One of the nice features of this API is any key:value that does not have data will return a string of "None".  This almost eliminates all key:value errors. Any valid endpoint will at the very least return "None".
I've set the polling sleep time on this one to 12 hours.

add rocketlaunch.live free API example

---

examples/wifi/expanded/requests_wifi_api_twitch.py

Requires Twitch developer account and oauth token. Instructions in code comments. 
Only pulls your own followers as a simple example.
- pretty serial hierarchy view
- shouty constants to make Pylint happy.
Attempted to ensure it meets Circuit Python current syntax styling including changing everything to f-strings, using settings.toml, basic doc strings for functions, sorted imports.
```
✅ Wifi!
| Attempting Bearer Token Request!
| 🔑 Token Authorized!
| Token Expires in: 64.6 days
| Attempting to GET Twitch JSON!
| ✅ Twitch JSON!
|  | Followers: 63
✂️ Disconnected from Twitch API
Finished!
Board Uptime: 5 hours
Next Update: 15 minutes
===============================
```

Update Twitch API Example with Connection Manager

---

examples/wifi/expanded/requests_wifi_api_youtube.py

Private API. Youtube/Google developer API Key required (created from developer dashboard).
Youtube/Google developer dashboard url in code comments. 
Pulls your own basic channel data including total videos, views, subscribers, All the basic info needed to get started.
Matching result is for matching username search. As long as you provide the API key it should only return 1 result associated with that username and key.
Added
- pretty serial hierarchy view
- improved and streamlined debugging
- shouty constants to make Pylint happy.
- imports sorted
- doc strings for functions
- uses settings.toml by default
- using Connection Manager by default
```
✅ Wifi!
| Attempting to GET YouTube JSON...
| ✅ YouTube …
```

Update YouTube API Example with Connection Manager

---

examples/wifi/expanded/requests_wifi_api_rocketlaunch_live.py

Using newer time_calc function, relabeled some variables, fixed os.getenv defaults for CIRCUITPY_ variables. made sleep_time shouty. board uptime displays time_calc human readable instead of monotonic seconds.
Discovered Rocket Launch Open, Close, and T-Zero window can be a combination of any of the 3.  Sometimes there's an open and close window, sometimes there's only a T-Zero, sometimes there's a Window Open and T-Zero, sometimes T-Zero and Window Close... Sometimes they include T0 in the time... So just accounted for all the possibilities and call it done.  If one, more, or all of the variables are None or aren't used then it won't be displayed.
Tested and reconfirmed everything works as it should
```
===============================
✅ Wifi!
| Attempting to GET …
```

minor updates for RocketLaunchLive API

---

examples/wifi/expanded/requests_wifi_adafruit_discord_active_online.py
examples/wifi/expanded/requests_wifi_api_discord.py
examples/wifi/expanded/requests_wifi_api_fitbit.py
examples/wifi/expanded/requests_wifi_api_github.py
examples/wifi/expanded/requests_wifi_api_mastodon.py
examples/wifi/expanded/requests_wifi_api_premiereleague.py
examples/wifi/expanded/requests_wifi_api_steam.py
examples/wifi/expanded/requests_wifi_api_twitch.py
examples/wifi/expanded/requests_wifi_api_youtube.py

It seems like these are unnecessary. I didn't notice it in some of the other recent updates so these ones already were merged with it. 
This PR removes the ones currently merged.

Remove pylint disable

---

examples/wifi/expanded/requests_wifi_api_openskynetwork_private_area.py

Private API, website credentials required. Instructions in code comments. More daily calls than Public API.
Pulls flight data from a geographic area. Example is around Orlando airport.
Added
- pretty serial hierarchy view
- improved endpoints with server side failure messages
- improved and streamlined debugging
- shouty constants to make Pylint happy.
- imports sorted
- switched from circuitpython_base64 to adafruit_binascii for base64 credential encoding
- doc strings for functions
- uses settings.toml by default
- now using Connection Manager by default
Changed from circuitpython_base64 community library to adafruit_binascii. It encodes to base64 much faster and has Adafruit library support.  It's a better way to go for examples needing base64 …

Update Open-Sky Network Private Area API Example 

---

examples/wifi/expanded/requests_wifi_multiple_cookies.py

Example for requesting cookies in a GET request. Updated to Connection Manager for 9.0
Added
- pretty serial hierarchy view
- added disable=import-error to make Pylint happy.
- imports sorted
- uses settings.toml by default
- using Connection Manager by default
- cookie emoji
```
✅ Wifi!
| Fetching Cookies: https://www.adafruit.com
| Total Cookies: 3
--------------------------------------------------------------------------------
| 🍪 zenid=cqf625rcrijkg48l4gto; expires=Mon, 08-Apr-2024 07:22:59 GMT; Max-Age=1209600; path=/; domain=.adafruit.com; secure; HttpOnly
--------------------------------------------------------------------------------
| 🍪 cart_count=0; expires=Mon, 08-Apr-2024 07:22:59 GMT; …
```

Update multiple cookies example

---

examples/wifi/requests_wifi_simpletest.py

Updating wifi_simpletest to 9.0 with Connection Manager
Added
- uses f-strings for formatting
- pretty serial hierarchy view with emojis (for IDE's that support them)
- shouty constants to make Pylint happy.
- imports sorted
- uses settings.toml by default
- using Connection Manager by default
```
Signal Strength: -58
✅ Wifi!
| GET Text Test: http://wifitest.adafruit.com/testwifi/index.html
| ✅ GET Response: This is a test of Adafruit WiFi!
If you can read this, its working :)
| ✂️ Disconnected from http://wifitest.adafruit.com/testwifi/index.html
--------------------------------------------------------------------------------
| GET Full Response Test: https://httpbin.org/get
| ✅ Unparsed Full JSON …
```

update wifi_simpletest with Connection Manager

---

adafruit_requests.py
examples/cpython/requests_cpython_advanced.py
examples/cpython/requests_cpython_simpletest.py
examples/esp32spi/requests_esp32spi_advanced.py
examples/esp32spi/requests_esp32spi_simpletest.py
examples/fona/requests_fona_advanced.py
examples/fona/requests_fona_simpletest.py
examples/wifi/expanded/requests_wifi_adafruit_discord_active_online.py
examples/wifi/expanded/requests_wifi_api_discord.py
examples/wifi/expanded/requests_wifi_api_fitbit.py
examples/wifi/expanded/requests_wifi_api_github.py
examples/wifi/expanded/requests_wifi_api_mastodon.py
examples/wifi/expanded/requests_wifi_api_openskynetwork_private.py
examples/wifi/expanded/requests_wifi_api_openskynetwork_private_area.py
examples/wifi/expanded/requests_wifi_api_openskynetwork_public.py
examples/wifi/expanded/requests_wifi_api_premiereleague.py
examples/wifi/expanded/requests_wifi_api_rocketlaunch_live.py
examples/wifi/expanded/requests_wifi_api_steam.py
examples/wifi/expanded/requests_wifi_api_twitch.py
examples/wifi/expanded/requests_wifi_api_youtube.py
examples/wifi/expanded/requests_wifi_multiple_cookies.py
examples/wifi/requests_wifi_advanced.py
examples/wifi/requests_wifi_simpletest.py
examples/wiznet5k/requests_wiznet5k_advanced.py
examples/wiznet5k/requests_wiznet5k_simpletest.py

Update the examples to use `with request.method as response:` and removed the close in the `Response.json()` as it doesn't match CPython
Tested the wifi standard and advanced and the rocketlive in advanced
fixes #186

Use with in examples, remove close in json()

---

examples/wifi/expanded/requests_wifi_api_queuetimes.py

Used for Disney theme park queue times. Public API.  Runs infinitely until time to update.  The way this one works is slightly different from most examples.  It's designed for a small display to take to the theme park and get updates on queue times.  
Here's an [example on a display](https://github.com/DJDevon3/My_Circuit_Python_Projects/tree/main/Boards/espressif/Unexpected%20Maker%20Feather%20S3/4.0%20ST7796S/QueueTimes%20API%20Display).
Inspired by Reddit user [Fishing_Quiet asked for help getting this API working on a display](https://www.reddit.com/r/circuitpython/comments/1bkpynl/updating_json_file/).

add Queue-Times API Example

---

adafruit_requests.py
tests/files_test.py

Add ability to post a file via the data param
- Broke some common functionality into reusable blocks
- if the `data` object has `read` send it up as raw data, reading in chuncks

Add ability to post a file via the data param

---

examples/wifi/expanded/requests_wifi_rachio_irrigation.py

Example pulls data from your Rachio Irrigation Timer. This is just a basic example. More can be done with zone scheduling, actually running the irrigation system, etc.. will work on an advanced example in the future.  This should be good enough for very basic communication with the API and timer.
Because this API pulls very sensitive data I've included an asterix obfuscation for serial prints when not in debug mode.  Debug mode will show all data without obfuscation.  The below serial output is verbose, the asterix are intentionally part of the script.
Example serial output:
```
✅ Wifi!
| Attempting to GET Rachio Authorization
| ✅ Authorized
| Attempting to GET Rachio JSON
| ✅ Rachio JSON
|  | UserID:  130*********************************
|  | Username: …
```

Add Rachio Irrigation API Example

---

examples/wifi/expanded/requests_wifi_rachio_irrigation.py

After adding the rate limiting endpoints to I realized making 2 requests per iteration cut down the total daily calls from 1700 to 850. By forcing a user to first get the PERSONID and paste it into settings.toml that allows for a true 1700 limit by making 1 request per run instead of 2.  I never came remotely close to approaching 850 per day but if a user reads the Rachio API documentation they'll be expecting to have 1700 requests per day at their disposal, this fixes that.
I tried to somewhat automate the process. The first run will only show the PersonID and instruct the user to paste the ID/Token into Settings.toml.  After that is done then it will ignore the first request every iteration.
The reason for the 'if RACHIO_PERSONID is None or RACHIO_PERSONID == "":' is because sometimes …

Update Rachio example with Rate Limit endpoints, fixed 1700 daily requests

---

adafruit_requests.py

The socket property is a CircuitPython addition not present in "standard requests" (which provides similar but not quite identical functionality via the "raw" property of response objects).
As discussed in the linked issue, having a documented way to access the underlying socket is needed for MP3 streaming over http/https.
Closes #198

Document socket property of Response objects

---

adafruit_requests.py

Fix cases in Session.request method where an exception could lead to exiting the method without the created socket being owned by a response or closed.  This would then cause future calls to get a socket with the same parameters to fail because one already existed and hadn't been closed.  The PR https://github.com/adafruit/Adafruit_CircuitPython_Requests/pull/72 fixed this issue for one case where an exception could be raised. This generalizes that in an attempt to fix it in other cases that could still be hit.

Fixes for exceptions in Session.request leading to sockets not properly closed

---

examples/esp32spi/requests_esp32spi_advanced.py
examples/esp32spi/requests_esp32spi_simpletest.py

Now need to use `.ap_info.rssi` and `.ap_info.ssid` instead of just `.rssi` and `.ssid`.
Tested on a Matrix Portal M4.
At least one of these examples is used in a Guide page.

update examples to use ap_info

---

tests/local_test_server.py
tests/real_call_test.py

Make our own little test server to run the test against instead of relying on 3rd party httpbin.

use a local test server instead of httpbin
